### ISSUE TITLE
Can't import CSV

### ISSUE THREAD

**Issue by SkrewEverything** [lifepillar/CSVKeychain#1]
I have a .csv file to import into keychain. But after clicking on import, the .csv files are greyed out in the finder.

**macOS: 10.13.2(High Sierra)**

<img width="702" alt="1" src="https://user-images.githubusercontent.com/15038803/34479082-9ab40a9e-efca-11e7-842b-3cf5d9e2c2ff.png">

<img width="730" alt="2" src="https://user-images.githubusercontent.com/15038803/34479095-a44214b6-efca-11e7-9def-563e113683a0.png">

**Comment by lifepillar** [comment]
Please read the message at the top of the dialog carefully: you must first choose the keychain, and only in the next dialog the CSV.

Admittedly, the order may be counterintuitive. I will swap the two dialogs
