### ISSUE TITLE
The "Where" field is missing when exporting data.

### ISSUE THREAD

**Issue by Loupehope** [lifepillar/CSVKeychain#10]
This script will be terminated prematurely because the following error has occurred:
 
Cannot process file: mandatory "Where" field is missing.
(Error number: -2700)

This is on macOS 10.14.6.

**Comment by lifepillar** [comment]
The format of the CSV file to be imported cannot be arbitrary. Please see https://github.com/lifepillar/CSVKeychain/issues/2.
