### ISSUE TITLE
Script Error In New Versions of Safari

### ISSUE THREAD

**Issue by SPT212** [lifepillar/CSVKeychain#14]
Hi,

Your script is awesome, thank you! The recently built-in Safari import of passwords from Chrome does not work properly so I reverted back to your script and I get the error in the below/attached screenshot. Any help would be greatly appreciated. Thanks! 
<img width="1414" alt="Screen Capture 2021-04-04 at 6 00 06 PM" src="https://user-images.githubusercontent.com/46346007/113522610-005e7c00-9570-11eb-878d-825f10729a90.png">

**Comment by lifepillar** [comment]
I do not recognize the code or the script name as something that belongs to this project. Can you provide more details about what you are trying to do and how?

**Comment by SPT212** [comment]
My apologies, I meant to message the author of csv2keychain, not CSVKeychain. Thanks!


Sebastian Pinto-Thomaz
+1 (917) 589-2589
