### ISSUE TITLE
Import declares success but hasn't

### ISSUE THREAD

**Issue by nicohofdtz** [lifepillar/CSVKeychain#15]
I created a new keychain and a passwort item in this keychain.
I edited the exported csv, altered the entry and imported the csv to the same (also tried another new) keychain.
The script declares the import succeeded but the entry doesn't show in the keychain.

**Comment by lifepillar** [comment]
I cannot reproduce it in macOS Big Sur 11.2.3. Is the keychain unlocked before starting to import? Have you double-checked that altering the CSV does not introduce syntax errors? If the issue persists, please provide more details and a step-by-step way to reproduce it. Possibly include a sample exported CSV file as well.

**Comment by nicohofdtz** [comment]
Well, now that I went through the hole procedure again it worked. I can't think of an error I made earlier, as I only opened the exported file in VSCode, made some changes to the values and tried the reimport.
Anyway, now it worked, so I probably oversaw something.
Sorry for the false alarm.
