### ISSUE TITLE
Export iCloud or Local Items keychain won't work on macOS High Sierra

### ISSUE THREAD

**Issue by Nikscorp** [lifepillar/CSVKeychain#5]
Please, update readme with these workarounds to make it work on last macOS versions

[Get passwords from Safari](https://discussions.agilebits.com/discussion/comment/455305/#Comment_455305)

[Get passwords from iCloud keychain directly](https://discussions.agilebits.com/discussion/comment/455708/#Comment_455708)

**Comment by NSExceptional** [comment]
Bump

**Comment by lifepillar** [comment]
Ops, I’m sorry, this somehow fell off my radar. I’ll take a look on the weekend.
